site_name: Nodos Docs
theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/95688674?s=400&u=dbda967bb1f34e1f65123a93699169ea4762bdf2&v=4
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
extra_css:
- stylesheets/extra.css
plugins:
    - search
    - macros
extra:
    remote_images_folder: "https://github.com/nodos-dev/docs/blob/main/docs/images/"
    required_cpp_version: "C++20"
    applications_pane_name: "Apps"
    to_do_text: "More information will be written later."

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Development for Nodos:
    - development/index.md
    - Plugins:
      - development/plugins/index.md
    - Subsystems:
      - development/subsystems/index.md
      - "nos.sys.vulkan": development/subsystems/nos.sys.vulkan.md
    - Applications:
       development/process/index.md
  - Using Nodos: 
    - usages/index.md
    - "AI Models": usages/ai_models.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  
